#pragma once
#ifndef STATECONNEXION_HPP
# define STATECONNEXION_HPP

enum ESTATE
{
	BEGINNING = 0,
	CONNECT_OK = 1,
	PARAMETERS_SET = 2,
	RESPONSE_SET = 3,
	ID_SET = 4,
	POSITION_PACKET_SET = 5
};

#endif /* STATECONNEXION_HPP */